"use client";

import Link from "next/link";
import { ArrowRight, Check, FileText, HandCoins, HeartHandshake, LockKeyhole, MessageCircle, Users, WalletCards } from "lucide-react";
import { PublicFooter, PublicShell } from "./public-shell";
import { useLanguage } from "@/lib/i18n";
import { getPublicContent } from "@/lib/public-content";

export function PublicPage({ kind }: { kind: "about" | "features" }) {
    const { locale } = useLanguage(); const c = getPublicContent(locale);
    const isAbout = kind === "about";
    const title = isAbout ? (locale === "sw" ? "Teknolojia inayolinda nguvu ya pamoja." : "Technology that protects the power of together.") : (locale === "sw" ? "Kazi zote za VICOBA, kwa uwazi zaidi." : "The work of your VICOBA, made clearer.");
    const body = isAbout ? (locale === "sw" ? "VIKOBA360 inasaidia vikundi vya fedha za jamii kusimamia shughuli zao kwa uwazi, usalama na urahisi zaidi." : "VIKOBA360 helps community finance groups manage their everyday work with more clarity, security and ease.") : c.features.body;
    const cards = isAbout ? [["Uwazi", "Kila hatua ya fedha ina kumbukumbu inayoweza kueleweka na kufuatiliwa.", LockKeyhole], ["Jamii kwanza", "Tunajenga kwa taratibu halisi za vikundi vya akiba vya Tanzania.", HeartHandshake], ["Ukuaji wa pamoja", "Taarifa bora husaidia viongozi na wanachama kufanya maamuzi bora.", Users]] as const : [["Member management", "Profiles, roles and membership status in one current record.", Users], ["Contributions & shares", "Capture collections and ownership accurately.", WalletCards], ["Loans & repayments", "Applications, guarantors, approvals and schedules.", HandCoins], ["Reports & governance", "Useful reports, meeting records and a traceable history.", FileText]] as const;
    return <PublicShell><main className="public-inner-page"><section className="public-page-hero public-container"><span className="public-eyebrow">{isAbout ? (locale === "sw" ? "Kuhusu VIKOBA360" : "About VIKOBA360") : c.features.eyebrow}</span><h1>{title}</h1><p>{body}</p><Link className="public-button public-button-primary" href="/auth/register">{c.cta.primary}<ArrowRight size={17} /></Link></section><section className="public-container public-page-grid">{cards.map(([heading, text, Icon]) => <article key={heading}><span className="public-icon"><Icon size={21} /></span><h2>{heading}</h2><p>{text}</p></article>)}</section><section className="public-container public-page-band"><div><span className="public-eyebrow">{isAbout ? c.trust.eyebrow : c.process.eyebrow}</span><h2>{isAbout ? c.trust.title : (locale === "sw" ? "Mfumo unaokua pamoja na kikundi chako." : "A system that grows with your group.")}</h2></div><ul>{(isAbout ? c.trust.items : ["One shared record", "Role-based workflows", "Mobile-ready experience"]).map(item => <li key={item}><Check size={16} /> {item}</li>)}</ul></section></main><PublicFooter /></PublicShell>;
}

export function ContactPage() {
    const { locale } = useLanguage(); const c = getPublicContent(locale);
    return <PublicShell><main className="public-inner-page"><section className="public-page-hero public-container"><span className="public-eyebrow">{locale === "sw" ? "Mawasiliano" : "Contact"}</span><h1>{locale === "sw" ? "Tuongee kuhusu kikundi chako." : "Let’s talk about your group."}</h1><p>{locale === "sw" ? "Tuma ujumbe na timu yetu itakusaidia kuelewa hatua inayofuata." : "Send a note and our team will help you understand the next step."}</p></section><section className="public-contact-grid public-container"><form className="public-contact-form" onSubmit={event => event.preventDefault()}><label>{locale === "sw" ? "Jina kamili" : "Full name"}<input required name="name" /></label><label>Email<input required type="email" name="email" /></label><label>{locale === "sw" ? "Namba ya simu" : "Phone"}<input name="phone" inputMode="tel" /></label><label>{locale === "sw" ? "Jina la kikundi" : "Group name"}<input name="group" /></label><label>{locale === "sw" ? "Ujumbe" : "Message"}<textarea required name="message" rows={5} /></label><button className="public-button public-button-primary" type="submit">{locale === "sw" ? "Tuma ujumbe" : "Send message"}<ArrowRight size={17} /></button></form><aside className="public-contact-aside"><MessageCircle size={25} /><h2>{locale === "sw" ? "Tuko hapa kusaidia." : "We are here to help."}</h2><p>{c.footer.description}</p><div><strong>{locale === "sw" ? "Msaada wa mfumo" : "Platform support"}</strong><span>{locale === "sw" ? "Tutakusaidia kuelewa VIKOBA360." : "We can help you understand VIKOBA360."}</span></div><div><strong>{locale === "sw" ? "Anza sasa" : "Start now"}</strong><Link href="/auth/register">{c.cta.primary} <ArrowRight size={15} /></Link></div></aside></section></main><PublicFooter /></PublicShell>;
}
