"use client"
import { FormEvent, useEffect, useMemo, useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Check, Loader2, Plus, Search, X } from "lucide-react"
import { apiGet } from "@/lib/api/client"
import { fineService, memberService, type Fine, type Member } from "@/lib/api/services"
type Envelope<T> = { data?: T; message?: string }
const unwrap = <T,>(v: T | Envelope<T>) => (v && typeof v === "object" && "data" in v ? (v as Envelope<T>).data : v) as T
const money = (n: number, c = "TZS") => `${c} ${Number(n || 0).toLocaleString()}`
export default function FinesPage() {
  const qc = useQueryClient(); const [groupId, setGroupId] = useState(""); const [currency, setCurrency] = useState("TZS"); const [search, setSearch] = useState(""); const [open, setOpen] = useState(false)
  const [form, setForm] = useState({ groupMemberId: "", fineType: "Late Meeting", amount: "5000", reason: "" })
  useEffect(() => { try { const g = JSON.parse(localStorage.getItem("v360_currentGroup") || "{}"); setGroupId(String(g.id ?? g.groupId ?? localStorage.getItem("v360_currentGroupId") ?? "")); setCurrency(g.currency || "TZS") } catch {} }, [])
  const finesQ = useQuery({ queryKey: ["fines", groupId], queryFn: () => fineService.list(groupId), enabled: /^\d+$/.test(groupId) })
  const membersQ = useQuery({ queryKey: ["members", groupId], queryFn: async () => unwrap(await memberService.list(groupId)) || [], enabled: /^\d+$/.test(groupId) })
  const typesQ = useQuery({ queryKey: ["fine-types", groupId], queryFn: async () => unwrap(await apiGet<Envelope<Array<{ id: number; name: string }>>>(`/api/fines/types?groupId=${groupId}`)) || [], enabled: /^\d+$/.test(groupId) })
  const issue = useMutation({ mutationFn: () => fineService.create({ groupId, groupMemberId: form.groupMemberId, fineType: form.fineType, amount: Number(form.amount), reason: form.reason }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["fines", groupId] }); setOpen(false); setForm({ groupMemberId: "", fineType: "Late Meeting", amount: "5000", reason: "" }) } })
  const update = useMutation({ mutationFn: ({ id, status, paymentAmount }: { id: string; status?: string; paymentAmount?: number }) => fineService.update(id, { groupId, status, paymentAmount }), onSuccess: () => qc.invalidateQueries({ queryKey: ["fines", groupId] }) })
  const members = (membersQ.data || []) as Member[]; const fines = (finesQ.data || []) as Fine[]
  const visible = useMemo(() => fines.filter(f => `${f.memberName || ""} ${f.fineTypeName || f.type || ""} ${f.reference || ""}`.toLowerCase().includes(search.toLowerCase())), [fines, search])
  const outstanding = fines.reduce((n, f) => n + Number(f.balance ?? f.amount ?? 0), 0); const paid = fines.reduce((n, f) => n + Number(f.paidAmount || 0), 0)
  const submit = (e: FormEvent) => { e.preventDefault(); if (form.groupMemberId && Number(form.amount) > 0) issue.mutate() }
  return <main className="mx-auto max-w-7xl px-6 py-8"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-bold text-neutral-400">Community / Fines</p><h1 className="mt-2 text-2xl font-black">Penalties & Fines</h1><p className="text-xs text-neutral-400">Record, collect, and reconcile member penalties.</p></div><button onClick={() => setOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#087f5b] px-4 py-2.5 text-xs font-bold text-white"><Plus size={15}/> Issue fine</button></div>
  <div className="mb-8 grid grid-cols-2 gap-4 lg:grid-cols-4">{[["Total logged", `${fines.length} incidents`], ["Collected", money(paid, currency)], ["Outstanding", money(outstanding, currency)], ["Waived", money(fines.filter(f => f.status === "WAIVED").reduce((n, f) => n + Number(f.amount || 0), 0), currency)]].map(([a, b]) => <div key={a} className="rounded-xl border border-[#dfe8e2] bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">{a}</p><p className="mt-2 text-lg font-black">{b}</p></div>)}</div>
  <div className="mb-6 flex items-center rounded-xl border border-[#dfe8e2] bg-white p-4"><Search size={15} className="mr-2 text-neutral-400"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search member, type, or reference..." className="w-full text-xs outline-none"/></div>
  <div className="overflow-hidden rounded-xl border border-[#dfe8e2] bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b bg-neutral-50 text-[9px] uppercase text-neutral-400"><th className="p-4">Member</th><th className="p-4">Type / reference</th><th className="p-4 text-right">Amount</th><th className="p-4 text-right">Balance</th><th className="p-4">Issued</th><th className="p-4">Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{(finesQ.isLoading || membersQ.isLoading) && <tr><td colSpan={7} className="p-12 text-center"><Loader2 className="mx-auto animate-spin" size={20}/></td></tr>}{!finesQ.isLoading && visible.map(f => <tr key={f.id} className="border-b border-neutral-50"><td className="p-4 font-bold">{f.memberName || members.find(m => String(m.id) === String(f.groupMemberId || f.memberId))?.name || "Member"}<span className="block text-[10px] font-normal text-neutral-400">{f.membershipNumber || ""}</span></td><td className="p-4"><span className="font-semibold">{f.fineTypeName || f.type || "Penalty"}</span><span className="block text-[10px] text-neutral-400">{f.reference || "—"}</span></td><td className="p-4 text-right font-bold">{money(Number(f.amount), currency)}</td><td className="p-4 text-right font-black text-red-600">{money(Number(f.balance ?? f.amount), currency)}</td><td className="p-4">{f.fineDate || "—"}</td><td className="p-4"><span className="rounded bg-red-50 px-2 py-1 text-[9px] font-extrabold">{f.status || "UNPAID"}</span></td><td className="p-4 text-right">{["UNPAID", "PARTIAL"].includes(f.status || "UNPAID") && <><button onClick={() => { const n = window.prompt("Payment amount", String(f.balance ?? f.amount ?? 0)); if (n) update.mutate({ id: String(f.id), paymentAmount: Number(n) }) }} className="mr-1 rounded bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">Pay</button><button onClick={() => update.mutate({ id: String(f.id), status: "WAIVED" })} className="rounded border px-2 py-1 text-[10px] font-bold">Waive</button></>}</td></tr>)}{!finesQ.isLoading && !visible.length && <tr><td colSpan={7} className="p-12 text-center text-neutral-400">No fines found for this group.</td></tr>}</tbody></table></div></div>
  {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#122b1c]/30 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between border-b pb-3"><div><h2 className="text-sm font-extrabold">Issue a fine</h2><p className="text-[10px] text-neutral-400">Saved to the member ledger.</p></div><button type="button" onClick={() => setOpen(false)}><X size={18}/></button></div><label className="mb-1 block text-xs font-bold">Member</label><select required value={form.groupMemberId} onChange={e => setForm({ ...form, groupMemberId: e.target.value })} className="mb-4 w-full rounded-lg border p-2.5 text-xs"><option value="">Select member...</option>{members.map(m => <option key={m.id} value={m.id}>{m.name || m.fullName} ({m.memberNo || m.membershipNumber || ""})</option>)}</select><div className="grid grid-cols-2 gap-3"><div><label className="mb-1 block text-xs font-bold">Fine type</label><select value={form.fineType} onChange={e => setForm({ ...form, fineType: e.target.value })} className="w-full rounded-lg border p-2.5 text-xs">{(typesQ.data || []).map((t: any) => <option key={t.id} value={t.name}>{t.name}</option>)}{!(typesQ.data || []).length && ["Late Meeting", "Meeting Absence", "Late Contribution", "Late Loan Payment", "Other Penalty"].map(t => <option key={t}>{t}</option>)}</select></div><div><label className="mb-1 block text-xs font-bold">Amount ({currency})</label><input required min="1" type="number" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} className="w-full rounded-lg border p-2.5 text-xs"/></div></div><label className="mb-1 mt-4 block text-xs font-bold">Reason</label><textarea value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} rows={3} className="w-full rounded-lg border p-2.5 text-xs"/><button disabled={issue.isPending} className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg bg-[#087f5b] py-3 text-xs font-bold text-white disabled:opacity-50">{issue.isPending && <Loader2 size={14} className="animate-spin"/>}<Check size={14}/> Save fine to member ledger</button>{issue.isError && <p className="mt-3 text-xs text-red-600">{(issue.error as Error).message}</p>}</form></div>}</main>
}
